# Generated by Django 5.2.13 on 2026-04-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0008_exam_question_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('examiner', 'Examiner')], default='student', max_length=10),
        ),
    ]
